"""add project members and created_by

Revision ID: 09ce76286de5
Revises: 9b6a9f021816
Create Date: 2026-06-05 14:46:44.192545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ce76286de5'
down_revision: Union[str, Sequence[str], None] = '9b6a9f021816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='project_member_role'), nullable=False, comment='角色: admin/member/viewer'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='加入时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='项目成员'
    )
    op.add_column('projects', sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者'))
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_by')
    op.drop_table('project_members')
    # ### end Alembic commands ###
