"""数据工厂 model 补齐 — tool_scenario+is_saved

Revision ID: 150907334bbc
Revises: 27dce819bdb9
Create Date: 2026-06-05 13:04:26.106926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150907334bbc'
down_revision: Union[str, Sequence[str], None] = '27dce819bdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_factory_records', sa.Column('tool_scenario', sa.String(length=50), nullable=True, comment='使用场景标签'))
    op.add_column('data_factory_records', sa.Column('is_saved', sa.Boolean(), nullable=False, comment='是否已保存'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_factory_records', 'is_saved')
    op.drop_column('data_factory_records', 'tool_scenario')
    # ### end Alembic commands ###
