"""add knowledge base and settings models

Revision ID: 1e60fb8d6987
Revises: 653c7d19dbec
Create Date: 2026-06-04 17:17:37.926697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e60fb8d6987'
down_revision: Union[str, Sequence[str], None] = '653c7d19dbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
    sa.Column('chroma_collection_name', sa.String(length=200), nullable=False, comment='ChromaDB 集合名（UUID 格式）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_collection_name')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='文件名'),
    sa.Column('file_path', sa.String(length=1000), nullable=False, comment='存储路径'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='文本分块数'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_documents')
    op.drop_table('system_settings')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
