"""add document model

Revision ID: 237e90162b2f
Revises: 76a5b4ce917d
Create Date: 2026-06-04 17:01:31.369125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237e90162b2f'
down_revision: Union[str, Sequence[str], None] = '76a5b4ce917d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=1000), nullable=False, comment='服务端存储路径'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型: pdf/docx/md/yaml/csv'),
    sa.Column('content', sa.Text(), nullable=True, comment='解析后的纯文本内容'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
