"""add ai_evaluator models

Revision ID: 2a2d27402a75
Revises: 2e75f466af9f
Create Date: 2026-06-05 11:42:55.320429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2d27402a75'
down_revision: Union[str, Sequence[str], None] = '2e75f466af9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_evaluator_dify_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='配置名称'),
    sa.Column('api_url', sa.String(length=500), nullable=False, comment='Dify API URL'),
    sa.Column('api_key', sa.String(length=200), nullable=False, comment='Dify API Key'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_evaluator_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='对外会话 ID'),
    sa.Column('conversation_id', sa.String(length=100), nullable=True, comment='Dify Conversation ID'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='会话标题'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('ai_evaluator_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('conversation_id', sa.String(length=100), nullable=True, comment='Dify Conversation ID'),
    sa.Column('message_id', sa.String(length=100), nullable=True, comment='Dify Message ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_evaluator_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_evaluator_messages')
    op.drop_table('ai_evaluator_sessions')
    op.drop_table('ai_evaluator_dify_configs')
    # ### end Alembic commands ###
