"""add data_factory model

Revision ID: 2e75f466af9f
Revises: 37d171fbe97a
Create Date: 2026-06-05 11:39:29.450060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e75f466af9f'
down_revision: Union[str, Sequence[str], None] = '37d171fbe97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_factory_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户 ID'),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('tool_category', sa.String(length=50), nullable=False, comment='工具分类'),
    sa.Column('input_data', mysql.JSON(), nullable=True, comment='输入参数'),
    sa.Column('output_data', sa.Text(), nullable=True, comment='输出结果'),
    sa.Column('tags', sa.String(length=200), nullable=True, comment='标签（逗号分隔）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_factory_records')
    # ### end Alembic commands ###
