"""add ai_smart_mode models

Revision ID: 37d171fbe97a
Revises: b3a5d782adba
Create Date: 2026-06-05 11:34:34.347242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37d171fbe97a'
down_revision: Union[str, Sequence[str], None] = 'b3a5d782adba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_smart_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='关联项目'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='用例名称'),
    sa.Column('task_description', sa.Text(), nullable=True, comment='自然语言任务描述'),
    sa.Column('target_url', sa.String(length=500), nullable=True, comment='目标 URL'),
    sa.Column('execution_mode', sa.String(length=20), nullable=False, comment='执行模式: text/vision'),
    sa.Column('enable_gif', sa.Boolean(), nullable=False, comment='是否录制 GIF'),
    sa.Column('planned_tasks', mysql.JSON(), nullable=True, comment='AI 规划的任务步骤'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft/ready/running/completed/failed'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_smart_execution_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ai_case_id', sa.Integer(), nullable=True, comment='关联 AI 用例'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='关联项目'),
    sa.Column('task_description', sa.Text(), nullable=True, comment='执行的任务描述'),
    sa.Column('execution_mode', sa.String(length=20), nullable=False, comment='执行模式: text/vision'),
    sa.Column('enable_gif', sa.Boolean(), nullable=False, comment='是否录制 GIF'),
    sa.Column('steps_completed', sa.Integer(), nullable=False, comment='已完成步骤数'),
    sa.Column('planned_tasks', mysql.JSON(), nullable=True, comment='规划的任务步骤'),
    sa.Column('execution_log', mysql.LONGTEXT(), nullable=True, comment='执行日志（JSON 数组）'),
    sa.Column('gif_recording', sa.String(length=500), nullable=True, comment='GIF 录制文件路径'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/running/completed/failed/cancelled'),
    sa.Column('summary', sa.Text(), nullable=True, comment='执行总结'),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_case_id'], ['ai_smart_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_smart_execution_records')
    op.drop_table('ai_smart_cases')
    # ### end Alembic commands ###
