"""add ui_automation models

Revision ID: 3fd7ade1394d
Revises: 7a90c748911c
Create Date: 2026-06-05 11:11:27.394846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3fd7ade1394d'
down_revision: Union[str, Sequence[str], None] = '7a90c748911c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_automation_locator_strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.String(length=30), nullable=False, comment='id/name/css/xpath/class/text/link_text/partial_link_text/tag_name'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_notification_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notify_type', sa.String(length=30), nullable=False, comment='feishu/wechat/dingtalk'),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True, comment='目标 URL'),
    sa.Column('browser_type', sa.String(length=50), nullable=False, comment='chromium/firefox/webkit'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_element_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ui_automation_element_groups.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['ui_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('browser_type', sa.String(length=50), nullable=False),
    sa.Column('window_width', sa.Integer(), nullable=False),
    sa.Column('window_height', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False, comment='超时时间(毫秒)'),
    sa.Column('headless', sa.Boolean(), nullable=False, comment='是否无头模式'),
    sa.Column('screenshot_on_failure', sa.Boolean(), nullable=False),
    sa.Column('record_video', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['ui_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success/failed'),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['ui_automation_notification_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_page_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='页面名称'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='页面 URL'),
    sa.Column('generated_code', sa.Text(), nullable=True, comment='自动生成的 Page Object 代码'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['ui_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_test_suites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['ui_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='元素名称'),
    sa.Column('locator_type', sa.String(length=30), nullable=False, comment='id/name/css/xpath/class/text'),
    sa.Column('locator_value', sa.String(length=500), nullable=False, comment='定位器值'),
    sa.Column('backup_locators', mysql.JSON(), nullable=True, comment='备用定位器列表: [{type, value}]'),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True, comment='所在页面 URL'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['ui_automation_element_groups.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['ui_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_scheduled_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False, comment='cron/interval'),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active/paused'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['ui_automation_test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_test_scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('page_object_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_object_id'], ['ui_automation_page_objects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['ui_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_page_object_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_object_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=True, comment='元素别名'),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['ui_automation_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_object_id'], ['ui_automation_page_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_object_id', 'element_id', name='uq_po_element')
    )
    op.create_table('ui_automation_script_element_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True, comment='使用场景描述'),
    sa.ForeignKeyConstraint(['element_id'], ['ui_automation_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['ui_automation_test_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_script_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False, comment='click/input/select/wait/assert/scroll/hover/navigate/screenshot'),
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.Column('input_value', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True, comment='预期结果/断言值'),
    sa.Column('wait_seconds', sa.Float(), nullable=True, comment='等待时间(秒)'),
    sa.ForeignKeyConstraint(['element_id'], ['ui_automation_elements.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['ui_automation_test_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('test_data', mysql.JSON(), nullable=True, comment='测试数据（JSON）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['ui_automation_projects.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['ui_automation_test_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_suite_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['ui_automation_test_suites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['ui_automation_test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'test_case_id', name='uq_suite_ui_case')
    )
    op.create_table('ui_automation_test_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/running/completed/failed/aborted'),
    sa.Column('result', sa.String(length=20), nullable=True, comment='passed/failed'),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['ui_automation_test_suites.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['ui_automation_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_operation_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['ui_automation_test_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['ui_automation_script_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_automation_screenshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=False, comment='截图存储路径'),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['ui_automation_test_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['ui_automation_script_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ui_automation_screenshots')
    op.drop_table('ui_automation_operation_records')
    op.drop_table('ui_automation_test_executions')
    op.drop_table('ui_automation_suite_cases')
    op.drop_table('ui_automation_test_cases')
    op.drop_table('ui_automation_script_steps')
    op.drop_table('ui_automation_script_element_usages')
    op.drop_table('ui_automation_page_object_elements')
    op.drop_table('ui_automation_test_scripts')
    op.drop_table('ui_automation_scheduled_tasks')
    op.drop_table('ui_automation_elements')
    op.drop_table('ui_automation_test_suites')
    op.drop_table('ui_automation_page_objects')
    op.drop_table('ui_automation_notification_logs')
    op.drop_table('ui_automation_environments')
    op.drop_table('ui_automation_element_groups')
    op.drop_table('ui_automation_projects')
    op.drop_table('ui_automation_notification_configs')
    op.drop_table('ui_automation_locator_strategies')
    # ### end Alembic commands ###
