"""add rbac permission/role/user_role tables

Revision ID: 4a95d1c5b1e3
Revises: afda5e3d1da6
Create Date: 2026-06-05 16:29:54.979508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a95d1c5b1e3'
down_revision: Union[str, Sequence[str], None] = 'afda5e3d1da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbac_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='权限 ID'),
    sa.Column('codename', sa.String(length=100), nullable=False, comment='权限代码: project.create'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='权限名称'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename'),
    comment='权限定义'
    )
    op.create_table('rbac_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='角色 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='系统角色（不可删除）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='角色'
    )
    op.create_table('rbac_role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联 ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色 ID'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限 ID'),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色-权限关联'
    )
    op.create_table('rbac_user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户-角色关联'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rbac_user_roles')
    op.drop_table('rbac_role_permissions')
    op.drop_table('rbac_roles')
    op.drop_table('rbac_permissions')
    # ### end Alembic commands ###
