"""add test point, case, batch models

Revision ID: 653c7d19dbec
Revises: 237e90162b2f
Create Date: 2026-06-04 17:09:27.091743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '653c7d19dbec'
down_revision: Union[str, Sequence[str], None] = '237e90162b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型: extract_test_points / generate_test_cases'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: PENDING/RUNNING/COMPLETED/FAILED'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度百分比 0-100'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='总处理数量'),
    sa.Column('completed_count', sa.Integer(), nullable=False, comment='已完成数量'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True, comment='来源文档（AI 提取时关联）'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='测试点标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='测试点描述'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: HIGH/MEDIUM/LOW'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='分类: 功能/UI/性能/安全/兼容性'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='是否已人工校验确认'),
    sa.Column('verified_by', sa.String(length=100), nullable=True, comment='校验人'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='校验时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('test_point_id', sa.Integer(), nullable=False, comment='关联的测试点 ID'),
    sa.Column('case_number', sa.String(length=50), nullable=True, comment='用例编号: TC-{test_point_id}-{seq}'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='用例标题'),
    sa.Column('precondition', sa.Text(), nullable=True, comment='前置条件'),
    sa.Column('steps', mysql.JSON(), nullable=True, comment='测试步骤: [{step, expected_result}]'),
    sa.Column('expected_result', sa.Text(), nullable=True, comment='总体预期结果'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: HIGH/MEDIUM/LOW'),
    sa.Column('case_type', sa.String(length=50), nullable=True, comment='用例类型: 功能/性能/安全/兼容性/UI'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['test_point_id'], ['test_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases')
    op.drop_table('test_points')
    op.drop_table('task_batches')
    # ### end Alembic commands ###
