"""add FK ondelete for data_factory user_id, fix test_management plans creator_id nullable

Revision ID: 91a271f8e6e8
Revises: 98ed67a7a3a0
Create Date: 2026-06-05 12:30:08.838447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91a271f8e6e8'
down_revision: Union[str, Sequence[str], None] = '98ed67a7a3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_automation_notification_logs', 'config_id',
               existing_type=mysql.INTEGER(),
               comment='关联通知配置 ID（预留，通知配置管理待实现）',
               existing_comment='关联通知配置 ID',
               existing_nullable=False)
    op.create_foreign_key(None, 'data_factory_records', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    # 手动添加：test_management_plans.creator_id 改为 nullable（配合 ondelete="SET NULL"）
    op.alter_column('test_management_plans', 'creator_id',
               existing_type=mysql.INTEGER(),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_factory_records', type_='foreignkey')
    op.alter_column('app_automation_notification_logs', 'config_id',
               existing_type=mysql.INTEGER(),
               comment='关联通知配置 ID',
               existing_comment='关联通知配置 ID（预留，通知配置管理待实现）',
               existing_nullable=False)
    # ### end Alembic commands ###
    # 回退：test_management_plans.creator_id 改回 nullable=False
    op.alter_column('test_management_plans', 'creator_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
