"""add fk ondelete for all modules

Revision ID: 98ed67a7a3a0
Revises: 2a2d27402a75
Create Date: 2026-06-05 12:10:49.274639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98ed67a7a3a0'
down_revision: Union[str, Sequence[str], None] = '2a2d27402a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'test_management_plans', 'test_management_versions', ['version_id'], ['id'], ondelete='CASCADE')
    op.alter_column('test_management_plans', 'creator_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'test_management_plans', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'test_management_plans', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('test_management_reports', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('test_management_reports_ibfk_2'), 'test_management_reports', type_='foreignkey')
    op.drop_constraint(op.f('test_management_reports_ibfk_3'), 'test_management_reports', type_='foreignkey')
    op.drop_constraint(op.f('test_management_reports_ibfk_1'), 'test_management_reports', type_='foreignkey')
    op.create_foreign_key(None, 'test_management_reports', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'test_management_reports', 'test_management_runs', ['run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'test_management_reports', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('test_management_review_assignments', 'reviewer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('test_management_review_assignments_ibfk_2'), 'test_management_review_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'test_management_review_assignments', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('test_management_review_comments', 'author_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('test_management_review_comments_ibfk_1'), 'test_management_review_comments', type_='foreignkey')
    op.create_foreign_key(None, 'test_management_review_comments', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('test_management_reviews', 'creator_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('test_management_reviews_ibfk_1'), 'test_management_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'test_management_reviews', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.alter_column('test_management_run_case_histories', 'executed_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('test_management_run_case_histories_ibfk_1'), 'test_management_run_case_histories', type_='foreignkey')
    op.create_foreign_key(None, 'test_management_run_case_histories', 'users', ['executed_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('test_management_run_cases_ibfk_2'), 'test_management_run_cases', type_='foreignkey')
    op.create_foreign_key(None, 'test_management_run_cases', 'users', ['executed_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('test_management_runs_ibfk_1'), 'test_management_runs', type_='foreignkey')
    op.create_foreign_key(None, 'test_management_runs', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.alter_column('test_management_suites', 'author_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('test_management_suites_ibfk_2'), 'test_management_suites', type_='foreignkey')
    op.drop_constraint(op.f('test_management_suites_ibfk_1'), 'test_management_suites', type_='foreignkey')
    op.create_foreign_key(None, 'test_management_suites', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'test_management_suites', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('test_management_versions', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('test_management_versions_ibfk_1'), 'test_management_versions', type_='foreignkey')
    op.create_foreign_key(None, 'test_management_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('test_points_ibfk_1'), 'test_points', type_='foreignkey')
    op.drop_constraint(op.f('test_points_ibfk_2'), 'test_points', type_='foreignkey')
    op.create_foreign_key(None, 'test_points', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'test_points', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ui_automation_element_groups_ibfk_1'), 'ui_automation_element_groups', type_='foreignkey')
    op.drop_constraint(op.f('ui_automation_element_groups_ibfk_2'), 'ui_automation_element_groups', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_element_groups', 'ui_automation_element_groups', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ui_automation_element_groups', 'ui_automation_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ui_automation_elements_ibfk_1'), 'ui_automation_elements', type_='foreignkey')
    op.drop_constraint(op.f('ui_automation_elements_ibfk_2'), 'ui_automation_elements', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_elements', 'ui_automation_element_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ui_automation_elements', 'ui_automation_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ui_automation_environments_ibfk_1'), 'ui_automation_environments', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_environments', 'ui_automation_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ui_automation_notification_logs_ibfk_1'), 'ui_automation_notification_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_notification_logs', 'ui_automation_notification_configs', ['config_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ui_automation_operation_records_ibfk_2'), 'ui_automation_operation_records', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_operation_records', 'ui_automation_script_steps', ['step_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ui_automation_page_objects_ibfk_1'), 'ui_automation_page_objects', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_page_objects', 'ui_automation_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ui_automation_scheduled_tasks_ibfk_1'), 'ui_automation_scheduled_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_scheduled_tasks', 'ui_automation_test_suites', ['suite_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ui_automation_screenshots_ibfk_2'), 'ui_automation_screenshots', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_screenshots', 'ui_automation_script_steps', ['step_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ui_automation_script_steps_ibfk_1'), 'ui_automation_script_steps', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_script_steps', 'ui_automation_elements', ['element_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ui_automation_test_cases_ibfk_2'), 'ui_automation_test_cases', type_='foreignkey')
    op.drop_constraint(op.f('ui_automation_test_cases_ibfk_1'), 'ui_automation_test_cases', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_test_cases', 'ui_automation_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ui_automation_test_cases', 'ui_automation_test_scripts', ['script_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ui_automation_test_executions_ibfk_1'), 'ui_automation_test_executions', type_='foreignkey')
    op.drop_constraint(op.f('ui_automation_test_executions_ibfk_2'), 'ui_automation_test_executions', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_test_executions', 'ui_automation_test_suites', ['suite_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ui_automation_test_executions', 'ui_automation_test_cases', ['test_case_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ui_automation_test_scripts_ibfk_2'), 'ui_automation_test_scripts', type_='foreignkey')
    op.drop_constraint(op.f('ui_automation_test_scripts_ibfk_1'), 'ui_automation_test_scripts', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_test_scripts', 'ui_automation_page_objects', ['page_object_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ui_automation_test_scripts', 'ui_automation_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ui_automation_test_suites_ibfk_1'), 'ui_automation_test_suites', type_='foreignkey')
    op.create_foreign_key(None, 'ui_automation_test_suites', 'ui_automation_projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ui_automation_test_suites', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_test_suites_ibfk_1'), 'ui_automation_test_suites', 'ui_automation_projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_test_scripts', type_='foreignkey')
    op.drop_constraint(None, 'ui_automation_test_scripts', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_test_scripts_ibfk_1'), 'ui_automation_test_scripts', 'ui_automation_page_objects', ['page_object_id'], ['id'])
    op.create_foreign_key(op.f('ui_automation_test_scripts_ibfk_2'), 'ui_automation_test_scripts', 'ui_automation_projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_test_executions', type_='foreignkey')
    op.drop_constraint(None, 'ui_automation_test_executions', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_test_executions_ibfk_2'), 'ui_automation_test_executions', 'ui_automation_test_cases', ['test_case_id'], ['id'])
    op.create_foreign_key(op.f('ui_automation_test_executions_ibfk_1'), 'ui_automation_test_executions', 'ui_automation_test_suites', ['suite_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_test_cases', type_='foreignkey')
    op.drop_constraint(None, 'ui_automation_test_cases', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_test_cases_ibfk_1'), 'ui_automation_test_cases', 'ui_automation_projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('ui_automation_test_cases_ibfk_2'), 'ui_automation_test_cases', 'ui_automation_test_scripts', ['script_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_script_steps', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_script_steps_ibfk_1'), 'ui_automation_script_steps', 'ui_automation_elements', ['element_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_screenshots', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_screenshots_ibfk_2'), 'ui_automation_screenshots', 'ui_automation_script_steps', ['step_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_scheduled_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_scheduled_tasks_ibfk_1'), 'ui_automation_scheduled_tasks', 'ui_automation_test_suites', ['suite_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_page_objects', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_page_objects_ibfk_1'), 'ui_automation_page_objects', 'ui_automation_projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_operation_records', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_operation_records_ibfk_2'), 'ui_automation_operation_records', 'ui_automation_script_steps', ['step_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_notification_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_notification_logs_ibfk_1'), 'ui_automation_notification_logs', 'ui_automation_notification_configs', ['config_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_environments', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_environments_ibfk_1'), 'ui_automation_environments', 'ui_automation_projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_elements', type_='foreignkey')
    op.drop_constraint(None, 'ui_automation_elements', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_elements_ibfk_2'), 'ui_automation_elements', 'ui_automation_projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('ui_automation_elements_ibfk_1'), 'ui_automation_elements', 'ui_automation_element_groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'ui_automation_element_groups', type_='foreignkey')
    op.drop_constraint(None, 'ui_automation_element_groups', type_='foreignkey')
    op.create_foreign_key(op.f('ui_automation_element_groups_ibfk_2'), 'ui_automation_element_groups', 'ui_automation_projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('ui_automation_element_groups_ibfk_1'), 'ui_automation_element_groups', 'ui_automation_element_groups', ['parent_id'], ['id'])
    op.drop_constraint(None, 'test_points', type_='foreignkey')
    op.drop_constraint(None, 'test_points', type_='foreignkey')
    op.create_foreign_key(op.f('test_points_ibfk_2'), 'test_points', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('test_points_ibfk_1'), 'test_points', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'test_management_versions', type_='foreignkey')
    op.create_foreign_key(op.f('test_management_versions_ibfk_1'), 'test_management_versions', 'users', ['created_by'], ['id'])
    op.alter_column('test_management_versions', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'test_management_suites', type_='foreignkey')
    op.drop_constraint(None, 'test_management_suites', type_='foreignkey')
    op.create_foreign_key(op.f('test_management_suites_ibfk_1'), 'test_management_suites', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('test_management_suites_ibfk_2'), 'test_management_suites', 'projects', ['project_id'], ['id'])
    op.alter_column('test_management_suites', 'author_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'test_management_runs', type_='foreignkey')
    op.create_foreign_key(op.f('test_management_runs_ibfk_1'), 'test_management_runs', 'users', ['assignee_id'], ['id'])
    op.drop_constraint(None, 'test_management_run_cases', type_='foreignkey')
    op.create_foreign_key(op.f('test_management_run_cases_ibfk_2'), 'test_management_run_cases', 'users', ['executed_by'], ['id'])
    op.drop_constraint(None, 'test_management_run_case_histories', type_='foreignkey')
    op.create_foreign_key(op.f('test_management_run_case_histories_ibfk_1'), 'test_management_run_case_histories', 'users', ['executed_by'], ['id'])
    op.alter_column('test_management_run_case_histories', 'executed_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'test_management_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('test_management_reviews_ibfk_1'), 'test_management_reviews', 'users', ['creator_id'], ['id'])
    op.alter_column('test_management_reviews', 'creator_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'test_management_review_comments', type_='foreignkey')
    op.create_foreign_key(op.f('test_management_review_comments_ibfk_1'), 'test_management_review_comments', 'users', ['author_id'], ['id'])
    op.alter_column('test_management_review_comments', 'author_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'test_management_review_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('test_management_review_assignments_ibfk_2'), 'test_management_review_assignments', 'users', ['reviewer_id'], ['id'])
    op.alter_column('test_management_review_assignments', 'reviewer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'test_management_reports', type_='foreignkey')
    op.drop_constraint(None, 'test_management_reports', type_='foreignkey')
    op.drop_constraint(None, 'test_management_reports', type_='foreignkey')
    op.create_foreign_key(op.f('test_management_reports_ibfk_1'), 'test_management_reports', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('test_management_reports_ibfk_3'), 'test_management_reports', 'test_management_runs', ['run_id'], ['id'])
    op.create_foreign_key(op.f('test_management_reports_ibfk_2'), 'test_management_reports', 'projects', ['project_id'], ['id'])
    op.alter_column('test_management_reports', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'test_management_plans', type_='foreignkey')
    op.drop_constraint(None, 'test_management_plans', type_='foreignkey')
    op.drop_constraint(None, 'test_management_plans', type_='foreignkey')
    # ### end Alembic commands ###
