"""feat: 统一通知配置表 notification_configs

Revision ID: 9b6a9f021816
Revises: f5d097a4215d
Create Date: 2026-06-05 14:25:52.132556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b6a9f021816'
down_revision: Union[str, Sequence[str], None] = 'f5d097a4215d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='配置 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='配置名称'),
    sa.Column('config_type', sa.String(length=50), nullable=False, comment='feishu / dingtalk / wework / webhook / custom'),
    sa.Column('webhook_bots', mysql.JSON(), nullable=True, comment='Webhook 机器人列表 [{"name":"","url":"","enabled":true}]'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认配置'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='统一通知配置'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_configs')
    # ### end Alembic commands ###
