"""feat: add database indexes for foreign key columns

Revision ID: a8ce0e2fee05
Revises: ff1234567890
Create Date: 2026-06-05 18:57:39.293457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a8ce0e2fee05'
down_revision: Union[str, Sequence[str], None] = 'ff1234567890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_evaluator_messages_session_id'), 'ai_evaluator_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_evaluator_sessions_user_id'), 'ai_evaluator_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_smart_cases_project_id'), 'ai_smart_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_smart_execution_records_ai_case_id'), 'ai_smart_execution_records', ['ai_case_id'], unique=False)
    op.create_index(op.f('ix_ai_smart_execution_records_project_id'), 'ai_smart_execution_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_api_collections_parent_id'), 'api_collections', ['parent_id'], unique=False)
    op.create_index(op.f('ix_api_collections_project_id'), 'api_collections', ['project_id'], unique=False)
    op.create_index(op.f('ix_api_environments_project_id'), 'api_environments', ['project_id'], unique=False)
    op.create_index(op.f('ix_api_notification_logs_config_id'), 'api_notification_logs', ['config_id'], unique=False)
    op.create_index(op.f('ix_api_request_histories_project_id'), 'api_request_histories', ['project_id'], unique=False)
    op.create_index(op.f('ix_api_request_histories_request_id'), 'api_request_histories', ['request_id'], unique=False)
    op.create_index(op.f('ix_api_requests_collection_id'), 'api_requests', ['collection_id'], unique=False)
    op.create_index(op.f('ix_api_scheduled_tasks_request_id'), 'api_scheduled_tasks', ['request_id'], unique=False)
    op.create_index(op.f('ix_api_scheduled_tasks_suite_id'), 'api_scheduled_tasks', ['suite_id'], unique=False)
    op.create_index(op.f('ix_api_test_suites_project_id'), 'api_test_suites', ['project_id'], unique=False)
    op.create_index(op.f('ix_app_automation_component_libraries_project_id'), 'app_automation_component_libraries', ['project_id'], unique=False)
    op.create_index(op.f('ix_app_automation_devices_project_id'), 'app_automation_devices', ['project_id'], unique=False)
    op.create_index(op.f('ix_app_automation_elements_image_category_id'), 'app_automation_elements', ['image_category_id'], unique=False)
    op.create_index(op.f('ix_app_automation_elements_project_id'), 'app_automation_elements', ['project_id'], unique=False)
    op.create_index(op.f('ix_app_automation_image_categories_project_id'), 'app_automation_image_categories', ['project_id'], unique=False)
    op.create_index(op.f('ix_app_automation_packages_project_id'), 'app_automation_packages', ['project_id'], unique=False)
    op.create_index(op.f('ix_app_automation_scheduled_tasks_suite_id'), 'app_automation_scheduled_tasks', ['suite_id'], unique=False)
    op.create_index(op.f('ix_app_automation_screenshots_execution_id'), 'app_automation_screenshots', ['execution_id'], unique=False)
    op.create_index(op.f('ix_app_automation_suite_cases_suite_id'), 'app_automation_suite_cases', ['suite_id'], unique=False)
    op.create_index(op.f('ix_app_automation_suite_cases_test_case_id'), 'app_automation_suite_cases', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_app_automation_test_cases_device_id'), 'app_automation_test_cases', ['device_id'], unique=False)
    op.create_index(op.f('ix_app_automation_test_cases_package_id'), 'app_automation_test_cases', ['package_id'], unique=False)
    op.create_index(op.f('ix_app_automation_test_cases_project_id'), 'app_automation_test_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_app_automation_test_executions_device_id'), 'app_automation_test_executions', ['device_id'], unique=False)
    op.create_index(op.f('ix_app_automation_test_executions_suite_id'), 'app_automation_test_executions', ['suite_id'], unique=False)
    op.create_index(op.f('ix_app_automation_test_executions_test_case_id'), 'app_automation_test_executions', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_app_automation_test_suites_project_id'), 'app_automation_test_suites', ['project_id'], unique=False)
    op.alter_column('ci_api_tokens', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='创建用户 ID',
               existing_nullable=True)
    op.alter_column('ci_api_tokens', 'last_used_at',
               existing_type=mysql.DATETIME(),
               comment='最后使用时间',
               existing_nullable=True)
    op.alter_column('ci_api_tokens', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否启用',
               existing_nullable=False)
    op.alter_column('ci_api_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment='过期时间',
               existing_nullable=True)
    op.alter_column('ci_api_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.create_index(op.f('ix_ci_api_tokens_user_id'), 'ci_api_tokens', ['user_id'], unique=False)
    op.alter_column('ci_pipeline_steps', 'module_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='模块类型: test_mgmt/api_testing/ui_auto/app_auto',
               existing_comment='模块类型',
               existing_nullable=False)
    op.alter_column('ci_pipeline_steps', 'module_config',
               existing_type=mysql.JSON(),
               comment='模块配置: {suite_id, plan_id, environment_id, ...}',
               existing_comment='模块配置',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='状态: pending/running/completed/failed/skipped',
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('ci_pipeline_steps', 'started_at',
               existing_type=mysql.DATETIME(),
               comment='开始时间',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='完成时间',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'duration_ms',
               existing_type=mysql.INTEGER(),
               comment='耗时(ms)',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.create_index(op.f('ix_ci_pipeline_steps_pipeline_id'), 'ci_pipeline_steps', ['pipeline_id'], unique=False)
    op.alter_column('ci_pipelines', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='状态: pending/running/completed/failed/aborted',
               existing_comment='pending/running/completed/failed/aborted',
               existing_nullable=False)
    op.add_column('ci_webhook_events', sa.Column('source_payload', mysql.JSON(), nullable=True, comment='原始请求 body'))
    op.add_column('ci_webhook_events', sa.Column('headers', mysql.JSON(), nullable=True, comment='请求头'))
    op.add_column('ci_webhook_events', sa.Column('ip_address', sa.String(length=50), nullable=True, comment='来源 IP'))
    op.alter_column('ci_webhook_events', 'ci_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='CI 类型: gitlab/github/jenkins',
               existing_comment='CI 类型',
               existing_nullable=False)
    op.alter_column('ci_webhook_events', 'event_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='事件类型（如 push/merge_request）',
               existing_nullable=True)
    op.alter_column('ci_webhook_events', 'pipeline_id',
               existing_type=mysql.INTEGER(),
               comment='关联管道 ID',
               existing_nullable=True)
    op.create_index(op.f('ix_ci_webhook_events_pipeline_id'), 'ci_webhook_events', ['pipeline_id'], unique=False)
    op.create_table_comment(
        'ci_webhook_events',
        'CI Webhook 事件记录',
        existing_comment='Webhook 事件记录',
        schema=None
    )
    op.drop_column('ci_webhook_events', 'raw_payload')
    op.drop_column('ci_webhook_events', 'source_ip')
    op.create_index(op.f('ix_data_factory_records_user_id'), 'data_factory_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_id'), 'knowledge_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_performance_executions_created_by'), 'performance_executions', ['created_by'], unique=False)
    op.create_index(op.f('ix_performance_executions_scene_id'), 'performance_executions', ['scene_id'], unique=False)
    op.create_index(op.f('ix_performance_jmx_files_created_by'), 'performance_jmx_files', ['created_by'], unique=False)
    op.create_index(op.f('ix_performance_jmx_files_project_id'), 'performance_jmx_files', ['project_id'], unique=False)
    op.alter_column('performance_reports', 'content',
               existing_type=mysql.JSON(),
               comment='详细报告内容（时间序列/分位值等）',
               existing_comment='详细报告内容',
               existing_nullable=True)
    op.create_index(op.f('ix_performance_reports_execution_id'), 'performance_reports', ['execution_id'], unique=False)
    op.alter_column('performance_scenes', 'config',
               existing_type=mysql.JSON(),
               comment='场景配置（URL/并发/持续时间等）',
               existing_comment='场景配置',
               existing_nullable=True)
    op.create_index(op.f('ix_performance_scenes_created_by'), 'performance_scenes', ['created_by'], unique=False)
    op.create_index(op.f('ix_performance_scenes_project_id'), 'performance_scenes', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_ra_analyses_document_id'), 'ra_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_ra_business_requirements_analysis_id'), 'ra_business_requirements', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ra_documents_uploader_id'), 'ra_documents', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_ra_generated_test_cases_requirement_id'), 'ra_generated_test_cases', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_ra_generated_test_cases_task_id'), 'ra_generated_test_cases', ['task_id'], unique=False)
    op.create_index(op.f('ix_ra_tasks_generation_config_id'), 'ra_tasks', ['generation_config_id'], unique=False)
    op.create_index(op.f('ix_ra_tasks_reviewer_config_id'), 'ra_tasks', ['reviewer_config_id'], unique=False)
    op.create_index(op.f('ix_ra_tasks_reviewer_prompt_id'), 'ra_tasks', ['reviewer_prompt_id'], unique=False)
    op.create_index(op.f('ix_ra_tasks_writer_config_id'), 'ra_tasks', ['writer_config_id'], unique=False)
    op.create_index(op.f('ix_ra_tasks_writer_prompt_id'), 'ra_tasks', ['writer_prompt_id'], unique=False)
    op.create_index(op.f('ix_rbac_role_permissions_permission_id'), 'rbac_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_rbac_role_permissions_role_id'), 'rbac_role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_rbac_user_roles_role_id'), 'rbac_user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_rbac_user_roles_user_id'), 'rbac_user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_batches_project_id'), 'task_batches', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_cases_project_id'), 'test_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_cases_test_point_id'), 'test_cases', ['test_point_id'], unique=False)
    op.create_index(op.f('ix_test_management_case_attachments_case_id'), 'test_management_case_attachments', ['case_id'], unique=False)
    op.create_index(op.f('ix_test_management_case_attachments_uploaded_by'), 'test_management_case_attachments', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_test_management_case_comments_author_id'), 'test_management_case_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_test_management_case_comments_case_id'), 'test_management_case_comments', ['case_id'], unique=False)
    op.create_index(op.f('ix_test_management_case_steps_case_id'), 'test_management_case_steps', ['case_id'], unique=False)
    op.create_index(op.f('ix_test_management_cases_author_id'), 'test_management_cases', ['author_id'], unique=False)
    op.create_index(op.f('ix_test_management_cases_project_id'), 'test_management_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_management_plans_creator_id'), 'test_management_plans', ['creator_id'], unique=False)
    op.create_index(op.f('ix_test_management_plans_project_id'), 'test_management_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_management_plans_version_id'), 'test_management_plans', ['version_id'], unique=False)
    op.create_index(op.f('ix_test_management_reports_created_by'), 'test_management_reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_test_management_reports_project_id'), 'test_management_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_management_reports_run_id'), 'test_management_reports', ['run_id'], unique=False)
    op.create_index(op.f('ix_test_management_review_assignments_review_id'), 'test_management_review_assignments', ['review_id'], unique=False)
    op.create_index(op.f('ix_test_management_review_assignments_reviewer_id'), 'test_management_review_assignments', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_test_management_review_cases_case_id'), 'test_management_review_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_test_management_review_cases_review_id'), 'test_management_review_cases', ['review_id'], unique=False)
    op.create_index(op.f('ix_test_management_review_comments_author_id'), 'test_management_review_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_test_management_review_comments_case_id'), 'test_management_review_comments', ['case_id'], unique=False)
    op.create_index(op.f('ix_test_management_review_comments_review_id'), 'test_management_review_comments', ['review_id'], unique=False)
    op.create_index(op.f('ix_test_management_review_projects_project_id'), 'test_management_review_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_management_review_projects_review_id'), 'test_management_review_projects', ['review_id'], unique=False)
    op.create_index(op.f('ix_test_management_reviews_creator_id'), 'test_management_reviews', ['creator_id'], unique=False)
    op.create_index(op.f('ix_test_management_run_case_histories_executed_by'), 'test_management_run_case_histories', ['executed_by'], unique=False)
    op.create_index(op.f('ix_test_management_run_case_histories_run_case_id'), 'test_management_run_case_histories', ['run_case_id'], unique=False)
    op.create_index(op.f('ix_test_management_run_cases_case_id'), 'test_management_run_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_test_management_run_cases_executed_by'), 'test_management_run_cases', ['executed_by'], unique=False)
    op.create_index(op.f('ix_test_management_run_cases_run_id'), 'test_management_run_cases', ['run_id'], unique=False)
    op.create_index(op.f('ix_test_management_runs_assignee_id'), 'test_management_runs', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_test_management_runs_plan_id'), 'test_management_runs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_test_management_suite_cases_case_id'), 'test_management_suite_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_test_management_suite_cases_suite_id'), 'test_management_suite_cases', ['suite_id'], unique=False)
    op.create_index(op.f('ix_test_management_suites_author_id'), 'test_management_suites', ['author_id'], unique=False)
    op.create_index(op.f('ix_test_management_suites_project_id'), 'test_management_suites', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_management_version_projects_project_id'), 'test_management_version_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_management_version_projects_version_id'), 'test_management_version_projects', ['version_id'], unique=False)
    op.create_index(op.f('ix_test_management_versions_created_by'), 'test_management_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_test_points_document_id'), 'test_points', ['document_id'], unique=False)
    op.create_index(op.f('ix_test_points_project_id'), 'test_points', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_element_groups_parent_id'), 'ui_automation_element_groups', ['parent_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_element_groups_project_id'), 'ui_automation_element_groups', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_elements_group_id'), 'ui_automation_elements', ['group_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_elements_project_id'), 'ui_automation_elements', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_environments_project_id'), 'ui_automation_environments', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_notification_logs_config_id'), 'ui_automation_notification_logs', ['config_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_operation_records_execution_id'), 'ui_automation_operation_records', ['execution_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_operation_records_step_id'), 'ui_automation_operation_records', ['step_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_page_object_elements_element_id'), 'ui_automation_page_object_elements', ['element_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_page_object_elements_page_object_id'), 'ui_automation_page_object_elements', ['page_object_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_page_objects_project_id'), 'ui_automation_page_objects', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_scheduled_tasks_suite_id'), 'ui_automation_scheduled_tasks', ['suite_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_screenshots_execution_id'), 'ui_automation_screenshots', ['execution_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_screenshots_step_id'), 'ui_automation_screenshots', ['step_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_script_element_usages_element_id'), 'ui_automation_script_element_usages', ['element_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_script_element_usages_script_id'), 'ui_automation_script_element_usages', ['script_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_script_steps_element_id'), 'ui_automation_script_steps', ['element_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_script_steps_script_id'), 'ui_automation_script_steps', ['script_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_suite_cases_suite_id'), 'ui_automation_suite_cases', ['suite_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_suite_cases_test_case_id'), 'ui_automation_suite_cases', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_test_cases_project_id'), 'ui_automation_test_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_test_cases_script_id'), 'ui_automation_test_cases', ['script_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_test_executions_suite_id'), 'ui_automation_test_executions', ['suite_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_test_executions_test_case_id'), 'ui_automation_test_executions', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_test_scripts_page_object_id'), 'ui_automation_test_scripts', ['page_object_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_test_scripts_project_id'), 'ui_automation_test_scripts', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_automation_test_suites_project_id'), 'ui_automation_test_suites', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ui_automation_test_suites_project_id'), table_name='ui_automation_test_suites')
    op.drop_index(op.f('ix_ui_automation_test_scripts_project_id'), table_name='ui_automation_test_scripts')
    op.drop_index(op.f('ix_ui_automation_test_scripts_page_object_id'), table_name='ui_automation_test_scripts')
    op.drop_index(op.f('ix_ui_automation_test_executions_test_case_id'), table_name='ui_automation_test_executions')
    op.drop_index(op.f('ix_ui_automation_test_executions_suite_id'), table_name='ui_automation_test_executions')
    op.drop_index(op.f('ix_ui_automation_test_cases_script_id'), table_name='ui_automation_test_cases')
    op.drop_index(op.f('ix_ui_automation_test_cases_project_id'), table_name='ui_automation_test_cases')
    op.drop_index(op.f('ix_ui_automation_suite_cases_test_case_id'), table_name='ui_automation_suite_cases')
    op.drop_index(op.f('ix_ui_automation_suite_cases_suite_id'), table_name='ui_automation_suite_cases')
    op.drop_index(op.f('ix_ui_automation_script_steps_script_id'), table_name='ui_automation_script_steps')
    op.drop_index(op.f('ix_ui_automation_script_steps_element_id'), table_name='ui_automation_script_steps')
    op.drop_index(op.f('ix_ui_automation_script_element_usages_script_id'), table_name='ui_automation_script_element_usages')
    op.drop_index(op.f('ix_ui_automation_script_element_usages_element_id'), table_name='ui_automation_script_element_usages')
    op.drop_index(op.f('ix_ui_automation_screenshots_step_id'), table_name='ui_automation_screenshots')
    op.drop_index(op.f('ix_ui_automation_screenshots_execution_id'), table_name='ui_automation_screenshots')
    op.drop_index(op.f('ix_ui_automation_scheduled_tasks_suite_id'), table_name='ui_automation_scheduled_tasks')
    op.drop_index(op.f('ix_ui_automation_page_objects_project_id'), table_name='ui_automation_page_objects')
    op.drop_index(op.f('ix_ui_automation_page_object_elements_page_object_id'), table_name='ui_automation_page_object_elements')
    op.drop_index(op.f('ix_ui_automation_page_object_elements_element_id'), table_name='ui_automation_page_object_elements')
    op.drop_index(op.f('ix_ui_automation_operation_records_step_id'), table_name='ui_automation_operation_records')
    op.drop_index(op.f('ix_ui_automation_operation_records_execution_id'), table_name='ui_automation_operation_records')
    op.drop_index(op.f('ix_ui_automation_notification_logs_config_id'), table_name='ui_automation_notification_logs')
    op.drop_index(op.f('ix_ui_automation_environments_project_id'), table_name='ui_automation_environments')
    op.drop_index(op.f('ix_ui_automation_elements_project_id'), table_name='ui_automation_elements')
    op.drop_index(op.f('ix_ui_automation_elements_group_id'), table_name='ui_automation_elements')
    op.drop_index(op.f('ix_ui_automation_element_groups_project_id'), table_name='ui_automation_element_groups')
    op.drop_index(op.f('ix_ui_automation_element_groups_parent_id'), table_name='ui_automation_element_groups')
    op.drop_index(op.f('ix_test_points_project_id'), table_name='test_points')
    op.drop_index(op.f('ix_test_points_document_id'), table_name='test_points')
    op.drop_index(op.f('ix_test_management_versions_created_by'), table_name='test_management_versions')
    op.drop_index(op.f('ix_test_management_version_projects_version_id'), table_name='test_management_version_projects')
    op.drop_index(op.f('ix_test_management_version_projects_project_id'), table_name='test_management_version_projects')
    op.drop_index(op.f('ix_test_management_suites_project_id'), table_name='test_management_suites')
    op.drop_index(op.f('ix_test_management_suites_author_id'), table_name='test_management_suites')
    op.drop_index(op.f('ix_test_management_suite_cases_suite_id'), table_name='test_management_suite_cases')
    op.drop_index(op.f('ix_test_management_suite_cases_case_id'), table_name='test_management_suite_cases')
    op.drop_index(op.f('ix_test_management_runs_plan_id'), table_name='test_management_runs')
    op.drop_index(op.f('ix_test_management_runs_assignee_id'), table_name='test_management_runs')
    op.drop_index(op.f('ix_test_management_run_cases_run_id'), table_name='test_management_run_cases')
    op.drop_index(op.f('ix_test_management_run_cases_executed_by'), table_name='test_management_run_cases')
    op.drop_index(op.f('ix_test_management_run_cases_case_id'), table_name='test_management_run_cases')
    op.drop_index(op.f('ix_test_management_run_case_histories_run_case_id'), table_name='test_management_run_case_histories')
    op.drop_index(op.f('ix_test_management_run_case_histories_executed_by'), table_name='test_management_run_case_histories')
    op.drop_index(op.f('ix_test_management_reviews_creator_id'), table_name='test_management_reviews')
    op.drop_index(op.f('ix_test_management_review_projects_review_id'), table_name='test_management_review_projects')
    op.drop_index(op.f('ix_test_management_review_projects_project_id'), table_name='test_management_review_projects')
    op.drop_index(op.f('ix_test_management_review_comments_review_id'), table_name='test_management_review_comments')
    op.drop_index(op.f('ix_test_management_review_comments_case_id'), table_name='test_management_review_comments')
    op.drop_index(op.f('ix_test_management_review_comments_author_id'), table_name='test_management_review_comments')
    op.drop_index(op.f('ix_test_management_review_cases_review_id'), table_name='test_management_review_cases')
    op.drop_index(op.f('ix_test_management_review_cases_case_id'), table_name='test_management_review_cases')
    op.drop_index(op.f('ix_test_management_review_assignments_reviewer_id'), table_name='test_management_review_assignments')
    op.drop_index(op.f('ix_test_management_review_assignments_review_id'), table_name='test_management_review_assignments')
    op.drop_index(op.f('ix_test_management_reports_run_id'), table_name='test_management_reports')
    op.drop_index(op.f('ix_test_management_reports_project_id'), table_name='test_management_reports')
    op.drop_index(op.f('ix_test_management_reports_created_by'), table_name='test_management_reports')
    op.drop_index(op.f('ix_test_management_plans_version_id'), table_name='test_management_plans')
    op.drop_index(op.f('ix_test_management_plans_project_id'), table_name='test_management_plans')
    op.drop_index(op.f('ix_test_management_plans_creator_id'), table_name='test_management_plans')
    op.drop_index(op.f('ix_test_management_cases_project_id'), table_name='test_management_cases')
    op.drop_index(op.f('ix_test_management_cases_author_id'), table_name='test_management_cases')
    op.drop_index(op.f('ix_test_management_case_steps_case_id'), table_name='test_management_case_steps')
    op.drop_index(op.f('ix_test_management_case_comments_case_id'), table_name='test_management_case_comments')
    op.drop_index(op.f('ix_test_management_case_comments_author_id'), table_name='test_management_case_comments')
    op.drop_index(op.f('ix_test_management_case_attachments_uploaded_by'), table_name='test_management_case_attachments')
    op.drop_index(op.f('ix_test_management_case_attachments_case_id'), table_name='test_management_case_attachments')
    op.drop_index(op.f('ix_test_cases_test_point_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_project_id'), table_name='test_cases')
    op.drop_index(op.f('ix_task_batches_project_id'), table_name='task_batches')
    op.drop_index(op.f('ix_rbac_user_roles_user_id'), table_name='rbac_user_roles')
    op.drop_index(op.f('ix_rbac_user_roles_role_id'), table_name='rbac_user_roles')
    op.drop_index(op.f('ix_rbac_role_permissions_role_id'), table_name='rbac_role_permissions')
    op.drop_index(op.f('ix_rbac_role_permissions_permission_id'), table_name='rbac_role_permissions')
    op.drop_index(op.f('ix_ra_tasks_writer_prompt_id'), table_name='ra_tasks')
    op.drop_index(op.f('ix_ra_tasks_writer_config_id'), table_name='ra_tasks')
    op.drop_index(op.f('ix_ra_tasks_reviewer_prompt_id'), table_name='ra_tasks')
    op.drop_index(op.f('ix_ra_tasks_reviewer_config_id'), table_name='ra_tasks')
    op.drop_index(op.f('ix_ra_tasks_generation_config_id'), table_name='ra_tasks')
    op.drop_index(op.f('ix_ra_generated_test_cases_task_id'), table_name='ra_generated_test_cases')
    op.drop_index(op.f('ix_ra_generated_test_cases_requirement_id'), table_name='ra_generated_test_cases')
    op.drop_index(op.f('ix_ra_documents_uploader_id'), table_name='ra_documents')
    op.drop_index(op.f('ix_ra_business_requirements_analysis_id'), table_name='ra_business_requirements')
    op.drop_index(op.f('ix_ra_analyses_document_id'), table_name='ra_analyses')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_performance_scenes_project_id'), table_name='performance_scenes')
    op.drop_index(op.f('ix_performance_scenes_created_by'), table_name='performance_scenes')
    op.alter_column('performance_scenes', 'config',
               existing_type=mysql.JSON(),
               comment='场景配置',
               existing_comment='场景配置（URL/并发/持续时间等）',
               existing_nullable=True)
    op.drop_index(op.f('ix_performance_reports_execution_id'), table_name='performance_reports')
    op.alter_column('performance_reports', 'content',
               existing_type=mysql.JSON(),
               comment='详细报告内容',
               existing_comment='详细报告内容（时间序列/分位值等）',
               existing_nullable=True)
    op.drop_index(op.f('ix_performance_jmx_files_project_id'), table_name='performance_jmx_files')
    op.drop_index(op.f('ix_performance_jmx_files_created_by'), table_name='performance_jmx_files')
    op.drop_index(op.f('ix_performance_executions_scene_id'), table_name='performance_executions')
    op.drop_index(op.f('ix_performance_executions_created_by'), table_name='performance_executions')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_data_factory_records_user_id'), table_name='data_factory_records')
    op.add_column('ci_webhook_events', sa.Column('source_ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True, comment='来源 IP'))
    op.add_column('ci_webhook_events', sa.Column('raw_payload', mysql.JSON(), nullable=True, comment='原始回调数据'))
    op.create_table_comment(
        'ci_webhook_events',
        'Webhook 事件记录',
        existing_comment='CI Webhook 事件记录',
        schema=None
    )
    op.drop_index(op.f('ix_ci_webhook_events_pipeline_id'), table_name='ci_webhook_events')
    op.alter_column('ci_webhook_events', 'pipeline_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联管道 ID',
               existing_nullable=True)
    op.alter_column('ci_webhook_events', 'event_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='事件类型（如 push/merge_request）',
               existing_nullable=True)
    op.alter_column('ci_webhook_events', 'ci_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='CI 类型',
               existing_comment='CI 类型: gitlab/github/jenkins',
               existing_nullable=False)
    op.drop_column('ci_webhook_events', 'ip_address')
    op.drop_column('ci_webhook_events', 'headers')
    op.drop_column('ci_webhook_events', 'source_payload')
    op.alter_column('ci_pipelines', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='pending/running/completed/failed/aborted',
               existing_comment='状态: pending/running/completed/failed/aborted',
               existing_nullable=False)
    op.drop_index(op.f('ix_ci_pipeline_steps_pipeline_id'), table_name='ci_pipeline_steps')
    op.alter_column('ci_pipeline_steps', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('ci_pipeline_steps', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'duration_ms',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='耗时(ms)',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'started_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='状态',
               existing_comment='状态: pending/running/completed/failed/skipped',
               existing_nullable=False)
    op.alter_column('ci_pipeline_steps', 'module_config',
               existing_type=mysql.JSON(),
               comment='模块配置',
               existing_comment='模块配置: {suite_id, plan_id, environment_id, ...}',
               existing_nullable=True)
    op.alter_column('ci_pipeline_steps', 'module_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='模块类型',
               existing_comment='模块类型: test_mgmt/api_testing/ui_auto/app_auto',
               existing_nullable=False)
    op.drop_index(op.f('ix_ci_api_tokens_user_id'), table_name='ci_api_tokens')
    op.alter_column('ci_api_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('ci_api_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='过期时间',
               existing_nullable=True)
    op.alter_column('ci_api_tokens', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False)
    op.alter_column('ci_api_tokens', 'last_used_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后使用时间',
               existing_nullable=True)
    op.alter_column('ci_api_tokens', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='创建用户 ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_app_automation_test_suites_project_id'), table_name='app_automation_test_suites')
    op.drop_index(op.f('ix_app_automation_test_executions_test_case_id'), table_name='app_automation_test_executions')
    op.drop_index(op.f('ix_app_automation_test_executions_suite_id'), table_name='app_automation_test_executions')
    op.drop_index(op.f('ix_app_automation_test_executions_device_id'), table_name='app_automation_test_executions')
    op.drop_index(op.f('ix_app_automation_test_cases_project_id'), table_name='app_automation_test_cases')
    op.drop_index(op.f('ix_app_automation_test_cases_package_id'), table_name='app_automation_test_cases')
    op.drop_index(op.f('ix_app_automation_test_cases_device_id'), table_name='app_automation_test_cases')
    op.drop_index(op.f('ix_app_automation_suite_cases_test_case_id'), table_name='app_automation_suite_cases')
    op.drop_index(op.f('ix_app_automation_suite_cases_suite_id'), table_name='app_automation_suite_cases')
    op.drop_index(op.f('ix_app_automation_screenshots_execution_id'), table_name='app_automation_screenshots')
    op.drop_index(op.f('ix_app_automation_scheduled_tasks_suite_id'), table_name='app_automation_scheduled_tasks')
    op.drop_index(op.f('ix_app_automation_packages_project_id'), table_name='app_automation_packages')
    op.drop_index(op.f('ix_app_automation_image_categories_project_id'), table_name='app_automation_image_categories')
    op.drop_index(op.f('ix_app_automation_elements_project_id'), table_name='app_automation_elements')
    op.drop_index(op.f('ix_app_automation_elements_image_category_id'), table_name='app_automation_elements')
    op.drop_index(op.f('ix_app_automation_devices_project_id'), table_name='app_automation_devices')
    op.drop_index(op.f('ix_app_automation_component_libraries_project_id'), table_name='app_automation_component_libraries')
    op.drop_index(op.f('ix_api_test_suites_project_id'), table_name='api_test_suites')
    op.drop_index(op.f('ix_api_scheduled_tasks_suite_id'), table_name='api_scheduled_tasks')
    op.drop_index(op.f('ix_api_scheduled_tasks_request_id'), table_name='api_scheduled_tasks')
    op.drop_index(op.f('ix_api_requests_collection_id'), table_name='api_requests')
    op.drop_index(op.f('ix_api_request_histories_request_id'), table_name='api_request_histories')
    op.drop_index(op.f('ix_api_request_histories_project_id'), table_name='api_request_histories')
    op.drop_index(op.f('ix_api_notification_logs_config_id'), table_name='api_notification_logs')
    op.drop_index(op.f('ix_api_environments_project_id'), table_name='api_environments')
    op.drop_index(op.f('ix_api_collections_project_id'), table_name='api_collections')
    op.drop_index(op.f('ix_api_collections_parent_id'), table_name='api_collections')
    op.drop_index(op.f('ix_ai_smart_execution_records_project_id'), table_name='ai_smart_execution_records')
    op.drop_index(op.f('ix_ai_smart_execution_records_ai_case_id'), table_name='ai_smart_execution_records')
    op.drop_index(op.f('ix_ai_smart_cases_project_id'), table_name='ai_smart_cases')
    op.drop_index(op.f('ix_ai_evaluator_sessions_user_id'), table_name='ai_evaluator_sessions')
    op.drop_index(op.f('ix_ai_evaluator_messages_session_id'), table_name='ai_evaluator_messages')
    # ### end Alembic commands ###
