"""add app_automation models

Revision ID: b3a5d782adba
Revises: 3fd7ade1394d
Create Date: 2026-06-05 11:27:43.690338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3a5d782adba'
down_revision: Union[str, Sequence[str], None] = '3fd7ade1394d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_automation_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('adb_path', sa.String(length=500), nullable=False),
    sa.Column('device_timeout', sa.Integer(), nullable=False, comment='设备超时(秒)'),
    sa.Column('screenshot_dir', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False, comment='关联通知配置 ID'),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success/failed'),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False, comment='android/ios'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_component_libraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('component_type', sa.String(length=20), nullable=False, comment='basic/custom'),
    sa.Column('config', mysql.JSON(), nullable=True, comment='组件配置'),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['app_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=200), nullable=False, comment='ADB 序列号/UDID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='设备名称'),
    sa.Column('platform', sa.String(length=20), nullable=False, comment='android/ios'),
    sa.Column('platform_version', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=False, comment='real/emulator'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='available/occupied/disconnected'),
    sa.Column('resolution', sa.String(length=50), nullable=True, comment='分辨率 1080x1920'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='设备 IP'),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['app_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_image_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['app_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=300), nullable=False, comment='Android package/ iOS bundle'),
    sa.Column('app_name', sa.String(length=200), nullable=False),
    sa.Column('main_activity', sa.String(length=300), nullable=True, comment='启动 Activity'),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['app_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_test_suites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['app_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='元素名称'),
    sa.Column('element_type', sa.String(length=20), nullable=False, comment='image/coordinate/region/text'),
    sa.Column('image_path', sa.String(length=500), nullable=True, comment='模板图片路径'),
    sa.Column('coordinates', mysql.JSON(), nullable=True, comment='坐标数据: {x,y} 或 {x,y,w,h}'),
    sa.Column('threshold', sa.Float(), nullable=True, comment='图像匹配阈值 0-1'),
    sa.Column('image_category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_category_id'], ['app_automation_image_categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['app_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_scheduled_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False, comment='cron/interval'),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active/paused'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['app_automation_test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('scene_data', mysql.JSON(), nullable=True, comment='场景编排步骤: [{action, element_id, params}]'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['app_automation_devices.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['app_automation_packages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['app_automation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_suite_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['app_automation_test_suites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['app_automation_test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'test_case_id', name='uq_app_suite_case')
    )
    op.create_table('app_automation_test_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/running/completed/failed'),
    sa.Column('result', sa.String(length=20), nullable=True, comment='passed/failed'),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['app_automation_devices.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['app_automation_test_suites.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['app_automation_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_automation_screenshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True, comment='步骤索引'),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['app_automation_test_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_automation_screenshots')
    op.drop_table('app_automation_test_executions')
    op.drop_table('app_automation_suite_cases')
    op.drop_table('app_automation_test_cases')
    op.drop_table('app_automation_scheduled_tasks')
    op.drop_table('app_automation_elements')
    op.drop_table('app_automation_test_suites')
    op.drop_table('app_automation_packages')
    op.drop_table('app_automation_image_categories')
    op.drop_table('app_automation_devices')
    op.drop_table('app_automation_component_libraries')
    op.drop_table('app_automation_projects')
    op.drop_table('app_automation_notification_logs')
    op.drop_table('app_automation_configs')
    # ### end Alembic commands ###
