"""add api_testing models

Revision ID: f3634490698b
Revises: 1e60fb8d6987
Create Date: 2026-06-04 20:32:59.726791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3634490698b'
down_revision: Union[str, Sequence[str], None] = '1e60fb8d6987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_notification_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='配置名称'),
    sa.Column('notify_type', sa.String(length=50), nullable=False, comment='通知类型: feishu/wechat/dingtalk'),
    sa.Column('webhook_url', sa.String(length=1024), nullable=False, comment='Webhook 地址'),
    sa.Column('secret', sa.String(length=256), nullable=True, comment='签名密钥'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('type', sa.String(length=50), nullable=True, comment='项目类型: HTTP/WebSocket/gRPC'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active/archived'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='集合名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父集合 ID（自引用实现树形）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['api_collections.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='关联项目 ID（null 表示全局环境）'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='环境名称'),
    sa.Column('env_type', sa.String(length=20), nullable=False, comment='类型: global/local'),
    sa.Column('variables', mysql.JSON(), nullable=True, comment='环境变量键值对'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False, comment='通知配置 ID'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: success/failed'),
    sa.Column('message', sa.Text(), nullable=True, comment='消息内容'),
    sa.Column('response', sa.Text(), nullable=True, comment='Webhook 响应'),
    sa.Column('sent_at', sa.DateTime(), nullable=False, comment='发送时间'),
    sa.ForeignKeyConstraint(['config_id'], ['api_notification_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_test_suites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='套件名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='套件描述'),
    sa.Column('request_ids', mysql.JSON(), nullable=True, comment='有序的请求 ID 列表'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False, comment='所属集合'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='请求名称'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP 方法'),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='请求 URL'),
    sa.Column('headers', mysql.JSON(), nullable=True, comment='请求头'),
    sa.Column('query_params', mysql.JSON(), nullable=True, comment='URL 查询参数'),
    sa.Column('body', mysql.JSON(), nullable=True, comment='请求体'),
    sa.Column('body_type', sa.String(length=50), nullable=True, comment='请求体类型: none/json/form-data/x-www-form-urlencoded/binary'),
    sa.Column('expected_response', mysql.JSON(), nullable=True, comment='预期响应（用于断言）'),
    sa.Column('is_favorite', sa.Boolean(), nullable=False, comment='是否收藏'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['collection_id'], ['api_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_request_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True, comment='关联请求 ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP 方法'),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='请求 URL（执行时的实际值）'),
    sa.Column('headers', mysql.JSON(), nullable=True, comment='请求头'),
    sa.Column('query_params', mysql.JSON(), nullable=True, comment='URL 查询参数'),
    sa.Column('body', mysql.JSON(), nullable=True, comment='请求体'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='响应状态码'),
    sa.Column('response_body', sa.Text(), nullable=True, comment='响应体文本'),
    sa.Column('response_headers', mysql.JSON(), nullable=True, comment='响应头'),
    sa.Column('elapsed_time', sa.Float(), nullable=True, comment='响应时间(ms)'),
    sa.Column('executed_at', sa.DateTime(), nullable=False, comment='执行时间'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['api_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_scheduled_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='任务名称'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型: suite/request'),
    sa.Column('suite_id', sa.Integer(), nullable=True, comment='关联套件 ID'),
    sa.Column('request_id', sa.Integer(), nullable=True, comment='关联请求 ID'),
    sa.Column('cron_expression', sa.String(length=100), nullable=False, comment="Cron 表达式: '0 9 * * 1-5'"),
    sa.Column('trigger_type', sa.String(length=20), nullable=False, comment='触发类型: cron/interval'),
    sa.Column('interval_seconds', sa.Integer(), nullable=True, comment='间隔秒数（trigger_type=interval 时使用）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active/paused'),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True, comment='上次执行时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['request_id'], ['api_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suite_id'], ['api_test_suites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_scheduled_tasks')
    op.drop_table('api_request_histories')
    op.drop_table('api_requests')
    op.drop_table('api_test_suites')
    op.drop_table('api_notification_logs')
    op.drop_table('api_environments')
    op.drop_table('api_collections')
    op.drop_table('api_projects')
    op.drop_table('api_notification_configs')
    # ### end Alembic commands ###
