"""feat: 新增 AI 用例生成模块 8 张表 (ra_ 前缀)

Revision ID: f5d097a4215d
Revises: 150907334bbc
Create Date: 2026-06-05 14:15:33.754274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5d097a4215d'
down_revision: Union[str, Sequence[str], None] = '150907334bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ra_ai_model_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='配置 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='配置名称'),
    sa.Column('model_type', sa.String(length=20), nullable=False, comment='deepseek/qwen/siliconflow/openai'),
    sa.Column('role', sa.String(length=30), nullable=False, comment='testcase_writer/testcase_reviewer/browser_use_text/browser_use_vision'),
    sa.Column('api_base', sa.String(length=500), nullable=False, comment='API 地址'),
    sa.Column('api_key', sa.String(length=500), nullable=False, comment='API 密钥'),
    sa.Column('model_name', sa.String(length=200), nullable=False, comment='模型名称'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='温度参数'),
    sa.Column('max_tokens', sa.Integer(), nullable=False, comment='最大 Token 数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI 模型配置'
    )
    op.create_table('ra_generation_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='配置 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='配置名称'),
    sa.Column('test_level', sa.String(length=50), nullable=False, comment='测试级别'),
    sa.Column('test_priority', sa.String(length=20), nullable=False, comment='优先级'),
    sa.Column('test_case_count', sa.Integer(), nullable=False, comment='生成用例数量'),
    sa.Column('auto_review', sa.Boolean(), nullable=False, comment='是否自动评审'),
    sa.Column('review_timeout', sa.Integer(), nullable=False, comment='评审超时（秒）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用（单例模式）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='生成行为配置'
    )
    op.create_table('ra_prompt_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='配置 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='配置名称'),
    sa.Column('prompt_type', sa.String(length=20), nullable=False, comment='testcase_writer/testcase_reviewer'),
    sa.Column('content', sa.Text(), nullable=False, comment='提示词内容'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='提示词配置'
    )
    op.create_table('ra_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='文档 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文档标题'),
    sa.Column('file', sa.String(length=500), nullable=True, comment='文件存储路径'),
    sa.Column('content', sa.Text(), nullable=True, comment='提取的文本内容'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='文件类型: pdf/docx/md/txt'),
    sa.Column('uploader_id', sa.Integer(), nullable=True, comment='上传者'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='需求文档（上传的原始文件 + 提取文本）'
    )
    op.create_table('ra_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增 ID'),
    sa.Column('task_id', sa.String(length=100), nullable=False, comment='任务唯一 ID'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='来源类型: document/text'),
    sa.Column('source_id', sa.Integer(), nullable=True, comment='来源 ID（analysis_id 或 null）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/generating/reviewing/revising/completed/failed/cancelled'),
    sa.Column('mode', sa.String(length=20), nullable=False, comment='stream/complete'),
    sa.Column('writer_config_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_config_id', sa.Integer(), nullable=True),
    sa.Column('writer_prompt_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_prompt_id', sa.Integer(), nullable=True),
    sa.Column('generation_config_id', sa.Integer(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True, comment='LLM 生成的原始内容'),
    sa.Column('review_feedback', sa.Text(), nullable=True, comment='AI 评审反馈'),
    sa.Column('final_test_cases', sa.Text(), nullable=True, comment='最终用例（Markdown）'),
    sa.Column('stream_buffer', sa.Text(), nullable=True, comment='流式缓冲（每500字符保存）'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度 0-100'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('is_saved_to_records', sa.Boolean(), nullable=False, comment='是否已保存到用例库'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['generation_config_id'], ['ra_generation_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_config_id'], ['ra_ai_model_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_prompt_id'], ['ra_prompt_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['writer_config_id'], ['ra_ai_model_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['writer_prompt_id'], ['ra_prompt_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI 用例生成任务'
    )
    op.create_index(op.f('ix_ra_tasks_task_id'), 'ra_tasks', ['task_id'], unique=True)
    op.create_table('ra_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='分析 ID'),
    sa.Column('document_id', sa.Integer(), nullable=True, comment='关联文档'),
    sa.Column('analysis_text', sa.Text(), nullable=True, comment='直接输入的文本（非文档）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/processing/completed/failed'),
    sa.Column('result', mysql.JSON(), nullable=True, comment='分析结果（提取的需求列表）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['ra_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='需求分析记录'
    )
    op.create_table('ra_business_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='需求 ID'),
    sa.Column('analysis_id', sa.Integer(), nullable=False, comment='关联分析'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='需求标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='需求描述'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: HIGH/MEDIUM/LOW'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类: 功能/性能/安全/兼容性/UI'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['analysis_id'], ['ra_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='业务需求'
    )
    op.create_table('ra_generated_test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用例 ID'),
    sa.Column('requirement_id', sa.Integer(), nullable=True, comment='关联需求'),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='关联生成任务'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='用例标题'),
    sa.Column('scenario', sa.Text(), nullable=True, comment='测试场景'),
    sa.Column('preconditions', sa.Text(), nullable=True, comment='前置条件'),
    sa.Column('steps', sa.Text(), nullable=True, comment='测试步骤'),
    sa.Column('expected_result', sa.Text(), nullable=True, comment='预期结果'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: HIGH/MEDIUM/LOW'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft/reviewed/approved/rejected'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['requirement_id'], ['ra_business_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['ra_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI 生成的测试用例'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ra_generated_test_cases')
    op.drop_table('ra_business_requirements')
    op.drop_table('ra_analyses')
    op.drop_index(op.f('ix_ra_tasks_task_id'), table_name='ra_tasks')
    op.drop_table('ra_tasks')
    op.drop_table('ra_documents')
    op.drop_table('ra_prompt_configs')
    op.drop_table('ra_generation_configs')
    op.drop_table('ra_ai_model_configs')
    # ### end Alembic commands ###
